# Global information unchanged during experiments

USER="root"

SWITCH_PRIVATEKEY=".ssh/switch-private-key"
CONNECTION_PRIVATEKEY=".ssh/connection-private-key"

MAIN_CLIENT="client0" # used in recovery mode
SECONDARY_CLIENT="client1"

# NOTE: must be consistent with each config.ini
SERVER0="server0"
SERVER1="server1"

LEAFSWITCH="tofino"
# NOTE:SPINESWITCH is not used at this stage
# SPINESWITCH="bf3" 

CLIENT_ROOTPATH="/root/farreach"
SWITCH_ROOTPATH="/root/farreach"
SERVER_ROOTPATH="/root/farreach"

# backup rocksdb after loading phase
BACKUPS_ROOTPATH="/tmp/rocksdbbackups"

# experiment
EVALUATION_SCRIPTS_PATH="${CLIENT_ROOTPATH}/scripts"
EVALUATION_OUTPUT_PREFIX="${CLIENT_ROOTPATH}/aeresults"

# network settings

MAIN_CLIENT_TOSWITCH_IFNAME="veth"
MAIN_CLIENT_TOSWITCH_IP="10.0.1.11"
MAIN_CLIENT_TOSWITCH_MAC="3c:fd:fe:bb:ca:78"
MAIN_CLIENT_TOSWITCH_FPPORT="1\/0"
MAIN_CLIENT_TOSWITCH_PIPEIDX="0"
MAIN_CLIENT_LOCAL_IP="172.20.20.11"

SECONDARY_CLIENT_TOSWITCH_IFNAME="veth"
SECONDARY_CLIENT_TOSWITCH_IP="10.0.1.12"
SECONDARY_CLIENT_TOSWITCH_MAC="9c:69:b4:60:34:f4"
SECONDARY_CLIENT_TOSWITCH_FPPORT="2\/0"
SECONDARY_CLIENT_TOSWITCH_PIPEIDX="0"
SECONDARY_CLIENT_LOCAL_IP="172.20.20.12"

SERVER0_TOSWITCH_IFNAME="veth"
SERVER0_TOSWITCH_IP="10.0.1.13"
SERVER0_TOSWITCH_MAC="9c:69:b4:60:34:e1"
SERVER0_TOSWITCH_FPPORT="3\/0"
SERVER0_TOSWITCH_PIPEIDX="0"
SERVER0_LOCAL_IP="172.20.20.13"

SERVER1_TOSWITCH_IFNAME="veth"
SERVER1_TOSWITCH_IP="10.0.1.14"
SERVER1_TOSWITCH_MAC="9c:69:b4:60:ef:c1"
SERVER1_TOSWITCH_FPPORT="4\/0"
SERVER1_TOSWITCH_PIPEIDX="0"
SERVER1_LOCAL_IP="172.20.20.14"

CONTROLLER_LOCAL_IP="172.20.20.13"
SWITCHOS_LOCAL_IP="172.20.20.100"
SWITCH_RECIRPORT_PIPELINE1TO0="21\/0"
SWITCH_RECIRPORT_PIPELINE0TO1="5\/0"

# CPU settings

SERVER0_WORKER_CORENUM="1"
SERVER0_TOTAL_CORENUM="2"
SERVER1_WORKER_CORENUM="1"
SERVER1_TOTAL_CORENUM="2"

is_global_included=1
